"""empty message

Revision ID: 4916586aa372
Revises: a7605b69543f
Create Date: 2020-02-19 07:08:11.216269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4916586aa372'
down_revision = 'a7605b69543f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_postgres_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('the_ec_gh')
    # ### end Alembic commands ###


def downgrade_postgres_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('the_ec_gh',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('other_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='the_ec_gh_pkey')
    )
    # ### end Alembic commands ###


def upgrade_mysql_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_mysql_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sqlite_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sqlite_bind():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

